title: Zhaobo Wang's Homepage
page-top-title: Zhaobo Wang
top-section-bg-text: Machine Learning
backgrounds:
  - static/assets/background/background_0.jpeg
  - static/assets/background/background_1.jpeg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Zhaobo Wang'
github-link:
  text: Github
  href: https://github.com/senli1073
license-link:
  text: License
  href: https://github.com/senli1073/senli1073.github.io/blob/main/LICENSE
sections:
  - id: home
    nav: HOME
    title: Zhaobo Wang&ensp;|&ensp;王照博
    href: '#page-top' # Default to '#<id>' if not specified
